/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2RouteImport } from './routes/v2'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BMTHIndexRouteImport } from './routes/BMTH/index'
import { Route as AdminOrderIdRouteImport } from './routes/admin/$orderId'
import { Route as BMTHOrderIdRouteImport } from './routes/BMTH/$orderId'

const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BMTHIndexRoute = BMTHIndexRouteImport.update({
  id: '/BMTH/',
  path: '/BMTH/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrderIdRoute = AdminOrderIdRouteImport.update({
  id: '/admin/$orderId',
  path: '/admin/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const BMTHOrderIdRoute = BMTHOrderIdRouteImport.update({
  id: '/BMTH/$orderId',
  path: '/BMTH/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/v2': typeof V2Route
  '/BMTH/$orderId': typeof BMTHOrderIdRoute
  '/admin/$orderId': typeof AdminOrderIdRoute
  '/BMTH/': typeof BMTHIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/v2': typeof V2Route
  '/BMTH/$orderId': typeof BMTHOrderIdRoute
  '/admin/$orderId': typeof AdminOrderIdRoute
  '/BMTH': typeof BMTHIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/v2': typeof V2Route
  '/BMTH/$orderId': typeof BMTHOrderIdRoute
  '/admin/$orderId': typeof AdminOrderIdRoute
  '/BMTH/': typeof BMTHIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/v2'
    | '/BMTH/$orderId'
    | '/admin/$orderId'
    | '/BMTH/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/v2'
    | '/BMTH/$orderId'
    | '/admin/$orderId'
    | '/BMTH'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/v2'
    | '/BMTH/$orderId'
    | '/admin/$orderId'
    | '/BMTH/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  V2Route: typeof V2Route
  BMTHOrderIdRoute: typeof BMTHOrderIdRoute
  AdminOrderIdRoute: typeof AdminOrderIdRoute
  BMTHIndexRoute: typeof BMTHIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/BMTH/': {
      id: '/BMTH/'
      path: '/BMTH'
      fullPath: '/BMTH/'
      preLoaderRoute: typeof BMTHIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$orderId': {
      id: '/admin/$orderId'
      path: '/admin/$orderId'
      fullPath: '/admin/$orderId'
      preLoaderRoute: typeof AdminOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/BMTH/$orderId': {
      id: '/BMTH/$orderId'
      path: '/BMTH/$orderId'
      fullPath: '/BMTH/$orderId'
      preLoaderRoute: typeof BMTHOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  V2Route: V2Route,
  BMTHOrderIdRoute: BMTHOrderIdRoute,
  AdminOrderIdRoute: AdminOrderIdRoute,
  BMTHIndexRoute: BMTHIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
